development:
  adapter: postgresql
  database: tripshare_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: tripshare_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tripshare_production
  pool: 5
  timeout: 5000